### ISSUE TITLE
perubahan filter di site semprot.com

### ISSUE THREAD

**Issue by cubakcabak** [heradhis/indonesianadblockrules#3]
||gambar123.com/pic/what/$domain=semprot.com|semprotku.com|64.237.43.94

semprot.com,semprotku.com,64.237.43.94##.cintasemprot_floating_banner_top, .cintasemprot_floating_banner_bottom, .cintasemprot_h, .cintasemprot_f, .semprot_ads_h, #cintasemprot_side_left, #cintasemprot_side_right, img[title="IndoBet - Agen Bola Online"], img[alt="Live Score"]

**Comment by bebaspuas20241** [comment]
siap jadi lamar

www,nobokep,my,id
