### ISSUE TITLE
Pls add file.rocks

### ISSUE THREAD

**Issue by p1nkyy** [heradhis/indonesianadblockrules#6]
Tolong bersihkan juga iklan2 di file.rocks. Situs sharing untuk file di google drive. Contoh link: https://file.rocks/file/0dHzrORcok. Bisa dilihat di tampilan kanan kiri content banyak banner iklan.

BTW, author bisa dihubungi di mana ya? Di Kaskus jg udah gak aktif keliatannya? :disappointed:

**Comment by gmarcher** [comment]
Silahkan diupdate filternya
